function createfigure_dist1D(X1,Y1,Y2,Y3,Y4,Y5)
%CREATEFIGURE(X1, Y1, X2, YMATRIX1, X3, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 27-Jun-2014 08:33:00

% Create figure
figure1 = figure('PaperType','A4','PaperSize',[11.692913 8.267716],...
  'PaperOrientation','landscape',...
  'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',1,'FontSize',20);

box(axes1,'on');
hold(axes1,'all');

% Create plot
%plot1 =  plot(X1,Y1,'Parent',axes1,'LineStyle','-','LineWidth',3,'DisplayName',' distance','Color',[0 0 0]);
% plot(X1,Y2,'Parent',axes1,'LineStyle','-','LineWidth',1.5,'DisplayName',' m =   1','Color',[0 0 1]);
% plot(X1,Y3,'Parent',axes1,'LineStyle','--','LineWidth',1.5,'DisplayName',' m =   2','Color',[1 0 0]);
% plot(X1,Y4,'Parent',axes1,'LineStyle','-.','LineWidth',1.5,'DisplayName',' m =   3','Color',[0 0.498039215803146 0]);
% plot(X1,Y5,'Parent',axes1,'LineStyle',':','LineWidth',1.5,'DisplayName',' m =  10','Color',[0.600000023841858 0.200000002980232 0]);


plot1 = plot(X1,[Y1 Y2 Y3 Y4 Y5],'Parent',axes1);
set(plot1(1),'LineWidth',4,'DisplayName',' distance','Color',[0 0 0]);
set(plot1(2),'LineWidth',2,'Color',[0 0 1],'DisplayName',' m^1');
set(plot1(3),'LineWidth',2,'LineStyle','--','Color',[1 0 0],'DisplayName',' m^2');
set(plot1(4),'LineWidth',2,'LineStyle','-.','Color',[0 0.498039215803146 0],'DisplayName',' m^3');
set(plot1(5),'LineWidth',2,'MarkerSize',8,'Marker','.','LineStyle',':',...
  'Color',[0.87058824300766 0.490196079015732 0],'DisplayName',' m^{10}');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 1 1],'LineWidth',1);

% Create plot
% Create plot
plot([-1,1],[0,0],'Parent',axes1,'MarkerFaceColor',[0 0 0],'MarkerSize',14,'Marker','o',...
  'LineStyle','none',...
  'Color',[0 0 0]);

% Create plot
%plot(figure1,[0,0],'Parent',axes1,'MarkerFaceColor',[0 0 0],'MarkerSize',14,'Marker','o',...
%  'LineStyle','none','Color',[0 0 0]);


% Create xlabel
xlabel('x','FontSize',24);

% Create ylabel
ylabel('d(x)','FontSize',24);


